//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timwi.Rank {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timwi.Rank.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html {
        ///    background: #eee;
        ///    margin: 0;
        ///    font-family: &apos;Work Sans&apos;, &apos;Trebuchet MS&apos;;
        ///}
        ///
        ///textarea, input, button {
        ///    font: inherit;
        ///}
        ///
        ///kbd {
        ///    font: inherit;
        ///    text-decoration: underline;
        ///}
        ///
        ///body {
        ///    max-width: 20cm;
        ///    margin: 0 auto;
        ///    padding: 1em 2em;
        ///    min-height: 100vh;
        ///    box-sizing: border-box;
        ///    background: white;
        ///    box-shadow: rgba(0, 0, 0, .4) 0 0 10px;
        ///}
        ///
        ///textarea {
        ///    width: 100%;
        ///    height: 20em;
        ///}
        ///
        ///input {
        ///    width: 100%;
        ///}
        ///
        ///li.incomp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RankCss {
            get {
                return ResourceManager.GetString("RankCss", resourceCulture);
            }
        }
    }
}
